services:
  frontend:
    build:
      context: ./SteCtyAreaFE/myapp
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  backend:
    build:
      context: ./SteCtyAreaBE/new
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8081:8081"
    restart: always

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/newwwww
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    depends_on:
      mysql-db:
        condition: service_healthy

    networks:
      - app-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newwwww

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge